version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    entrypoint: ["/bin/bash", "-c", "ollama serve & sleep 5 && ollama pull phi3 && ollama pull tinyllama && wait"]

  bot-api:
    build: ./bot-api
    container_name: bot-api
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
    restart: unless-stopped

  frontend:
    build: ./frontend-chat
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - bot-api
    environment:
      - VITE_API_URL=http://bot-api:8000
    restart: unless-stopped

volumes:
  ollama-data:
